---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nextcloud-storage
  resources:
    requests:
      storage: ${NEXTCLOUD_STORAGE_SIZE}Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-db
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nextcloud-storage
  resources:
    requests:
      storage: ${NEXTCLOUD_DB_SIZE}Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-redis
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nextcloud-storage
  resources:
    requests:
      storage: ${NEXTCLOUD_REDIS_SIZE}Gi