apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nextcloud-storage
  namespace: nextcloud
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true